const SIGNIN_REQ = "SIGNIN_REQ";
const SIGNIN_SUCCESS = "SIGNIN_SUCCESS";
const SIGNIN_FAILURE = "SIGNIN_FAILURE";
const SIGNOUT = "SIGNOUT";

export { SIGNIN_FAILURE, SIGNIN_SUCCESS, SIGNIN_REQ, SIGNOUT };
